name: Setup Node
description: Setup pnpm

inputs:
  pnpm-version:  
    description: Version of pnpm to use
    required: false
    default: '8.6.3'

runs:
  using: composite
  steps:    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}