name: Build

on:
  workflow_call:

jobs:
  build:
    name: "Build application"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1