name: Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["19.4.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Test unit
        run: pnpm run test
