name: Validate
on:
  push:
    branches:
      - refactor/create-actions

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    uses: ./.github/workflows/tests.yml

  build:     
    needs: ["unit-test"]
    uses: ./.github/workflows/build.yml

  # build:
  #   needs: ["build"]
  #   uses: ./.github/workflows/build.yml
